version: '3.8'

services:
  faq:
    container_name: faq
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .next:/app/.next
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    image: nest-pharmatech/faq:latest
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.faq.entrypoints=http'
      - 'traefik.http.routers.faq.rule=Host(`faq.trungthanhdev.com`)'
      - 'traefik.http.routers.faq-secure.entrypoints=https'
      - 'traefik.http.routers.faq-secure.rule=Host(`pharmatech.vn`)'
      - 'traefik.http.routers.faq-secure.tls.certresolver=letsencrypt'
networks:
  traefik:
    external: true