version: '3.8'

services:
  faq:
    container_name: faq
    image: nest-pharmatech/faq:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - NODE_ENV=production
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://thanhqt:pharmatech76@cluster0.iqxvxvt.mongodb.net/faq?retryWrites=true&w=majority
      - WP_USERNAME=thanhqt
      - WP_PASSWORD=pharmatech76
      - WP_URL=https://wordpress.pharmatech.vn
      - DEBUG=mongodb:*
      - NEXT_SHARP_PATH=/tmp/node_modules/sharp
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.faq.entrypoints=http'
      - 'traefik.http.routers.faq.rule=Host(`pharmatech.vn`)'
      - 'traefik.http.routers.faq-secure.entrypoints=https'
      - 'traefik.http.routers.faq-secure.rule=Host(`pharmatech.vn`)'
      - 'traefik.http.routers.faq-secure.tls.certresolver=letsencrypt'

networks:
  traefik:
    external: true