
services:
  faq:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: web
        PORT_PROGRAM: 7000:3000
    image: nest-pharmatech/faq:latest
    container_name: nextjs-faq
    ports:
      - '7000:3000'
    networks:
      - traefik
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.faq.entrypoints=http'
      - 'traefik.http.routers.faq.rule=Host(`faq.trungthanhdev.com`)'
      - 'traefik.http.routers.faq-secure.entrypoints=https'
      - 'traefik.http.routers.faq-secure.rule=Host(`pharmatech.vn`)'
      - 'traefik.http.routers.faq-secure.tls.certresolver=letsencrypt'
networks:
  traefik:
    external: true